#!/bin/zsh
#dep:gphoto2 ffmpeg
# use a camera accessible via gphoto2 as webcam
sudo modprobe v4l2loopback exclusive_caps=1
sudo gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0
