#!/bin/zsh
#dep:x-terminal-emulator tmux mosh
if [[ "$1" == "-S" ]]; then
	shift
	server=${1};
	shift
else
	server="qwerty";
fi

exec x-terminal-emulator -t Weechat -e tmux new-session mosh "${server}" -- tmux attach "$@" -t weechat
