#!/bin/zsh

source ${$(realpath "$0"):h:h}/lib/common.zsh

profile="${0:t}"

depend firefox firejail

mkdir -p $HOME/.jails/firefox-$profile

exec firejail --private=$HOME/.jails/firefox-$profile \
	firefox --class $profile --no-remote "$@"
