#!/bin/zsh

source ${$(realpath "$0"):h:h}/lib/common.zsh

profile="${0:t}"

depend chromium firejail

mkdir -p $HOME/.jails/chromium-$profile

exec firejail --private=$HOME/.jails/chromium-$profile \
	chromium "$@"
