#!/bin/zsh
source ${$(realpath "$0"):h:h}/lib/next-in-path.zsh
RIPGREP_CONFIG_PATH=${XDG_CONFIG_HOME:-$HOME/.config}/ripgreprc
if [[ -e $RIPGREP_CONFIG_PATH ]]; then
	export RIPGREP_CONFIG_PATH
fi
$(next-in-path rg $0) $@
