#!/bin/zsh

zparseopts -D -E \
	t:=title -title=title \
	e:=execute -exec=execute -execute=execute \
	c:=class -class=class


kitty -1 ${class+--class=}${class[2]} ${title+-T} ${title[2]} ${=execute[2]} "$@"
