#!/bin/zsh

if [[ "${0:t}" == "with-term" ]]; then
	echo "Symlink to g\$progname to start \$progname in a new terminal"
	echo "See g for launching with tmux"
	exit 1
fi

if [[ -e /etc/zsh/zprofile ]]; then
	. /etc/zsh/zprofile
fi
if [[ -e $HOME/.zshenv ]]; then
	. $HOME/.zshenv
fi

prog=${${0:t}[2,-1]}

exec x-terminal-emulator -t G${prog} -e $prog
